//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendoHealth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloodpressuredata
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<int> BPL { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<int> LP { get; set; }
        public string date { get; set; }
        public string Note { get; set; }
        public Nullable<int> BOUnit { get; set; }
    }
}
