//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendoHealth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class glycemiedata
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<int> BG { get; set; }
        public string DinnerSituation { get; set; }
        public string DrugsSituation { get; set; }
        public string date { get; set; }
        public string Note { get; set; }
        public Nullable<int> BGUnit { get; set; }
    }
}
