//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHendo.HendoHealth.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class medical_valuesEntities : DbContext
    {
        public medical_valuesEntities()
            : base("name=medical_valuesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bloodpressuredata> bloodpressuredata { get; set; }
        public virtual DbSet<glycemiedata> glycemiedata { get; set; }
        public virtual DbSet<pulseoximeterdata> pulseoximeterdata { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<weightdata> weightdata { get; set; }
    }
}
