//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendoHealth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pulseoximeterdata
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<int> SpO2 { get; set; }
        public Nullable<int> Pulse { get; set; }
        public Nullable<double> IP { get; set; }
        public string Note { get; set; }
        public string date { get; set; }
    }
}
