//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendoHealth.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class weightdata
    {
        public int Id { get; set; }
        public string username { get; set; }
        public Nullable<float> BMI { get; set; }
        public Nullable<double> BoneValue { get; set; }
        public Nullable<int> DCI { get; set; }
        public Nullable<double> FatValue { get; set; }
        public string date { get; set; }
        public Nullable<double> MuscleMass { get; set; }
        public string Note { get; set; }
        public Nullable<double> WaterValue { get; set; }
        public Nullable<double> WeightValue { get; set; }
        public Nullable<int> VGV { get; set; }
        public Nullable<int> WeightUnit { get; set; }
    }
}
