//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HendoHealth.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HendoHealth.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiActivity.
        /// </summary>
        internal static string APInameAR {
            get {
                return ResourceManager.GetString("APInameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiBG.
        /// </summary>
        internal static string APInameBG {
            get {
                return ResourceManager.GetString("APInameBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiSpO2.
        /// </summary>
        internal static string APInameBO {
            get {
                return ResourceManager.GetString("APInameBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiBP.
        /// </summary>
        internal static string APInameBP {
            get {
                return ResourceManager.GetString("APInameBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiFood.
        /// </summary>
        internal static string APInameFOOD {
            get {
                return ResourceManager.GetString("APInameFOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiSport.
        /// </summary>
        internal static string APInameSPORT {
            get {
                return ResourceManager.GetString("APInameSPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiSleep.
        /// </summary>
        internal static string APInameSR {
            get {
                return ResourceManager.GetString("APInameSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiUserInfo.
        /// </summary>
        internal static string APInameUserInfo {
            get {
                return ResourceManager.GetString("APInameUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OpenApiWeight.
        /// </summary>
        internal static string APInameWeight {
            get {
                return ResourceManager.GetString("APInameWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a e4dce2f7027044e0a6ce82e******.
        /// </summary>
        internal static string client_id {
            get {
                return ResourceManager.GetString("client_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a bb6a0326db55468f8f474a******.
        /// </summary>
        internal static string client_secret {
            get {
                return ResourceManager.GetString("client_secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.2; SV1; .NET CLR 1.1.4322; .NET CLR 2.0.50727).
        /// </summary>
        internal static string DefaultUserAgent {
            get {
                return ResourceManager.GetString("DefaultUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a authorization_code.
        /// </summary>
        internal static string granttypeauthorizationcode {
            get {
                return ResourceManager.GetString("granttypeauthorizationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:8080/HendoHealth/tokencallback.aspx********.
        /// </summary>
        internal static string redirect_uri {
            get {
                return ResourceManager.GetString("redirect_uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a code.
        /// </summary>
        internal static string responsetypecode {
            get {
                return ResourceManager.GetString("responsetypecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a refresh_token.
        /// </summary>
        internal static string responsetyperefreshtoken {
            get {
                return ResourceManager.GetString("responsetyperefreshtoken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 082a65ac25db4262b795f******.
        /// </summary>
        internal static string sc {
            get {
                return ResourceManager.GetString("sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 7862387hduewihidu********.
        /// </summary>
        internal static string sv_OpenApiActivity {
            get {
                return ResourceManager.GetString("sv_OpenApiActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 773278yhd87ey**********.
        /// </summary>
        internal static string sv_OpenApiBG {
            get {
                return ResourceManager.GetString("sv_OpenApiBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a n7c4389xj789r43ux4389u*********.
        /// </summary>
        internal static string sv_OpenApiBP {
            get {
                return ResourceManager.GetString("sv_OpenApiBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 8y3287yhdewuidehdu*********.
        /// </summary>
        internal static string sv_OpenApiFood {
            get {
                return ResourceManager.GetString("sv_OpenApiFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 79837892hduiwehduiwe*******.
        /// </summary>
        internal static string sv_OpenApiSleep {
            get {
                return ResourceManager.GetString("sv_OpenApiSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 78yudwekjcninciew*********.
        /// </summary>
        internal static string sv_OpenApiSpO2 {
            get {
                return ResourceManager.GetString("sv_OpenApiSpO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 7823yhd87huhewdew***********.
        /// </summary>
        internal static string sv_OpenApiSport {
            get {
                return ResourceManager.GetString("sv_OpenApiSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 7y238uidhduiehwduiwe*******.
        /// </summary>
        internal static string sv_OpenApiUserInfo {
            get {
                return ResourceManager.GetString("sv_OpenApiUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 78783278hduhwd**********.
        /// </summary>
        internal static string sv_OpenApiWeight {
            get {
                return ResourceManager.GetString("sv_OpenApiWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/user/{0}/activity.json/.
        /// </summary>
        internal static string urlardata {
            get {
                return ResourceManager.GetString("urlardata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/activity.json/.
        /// </summary>
        internal static string urlardataclient {
            get {
                return ResourceManager.GetString("urlardataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://oauthuser.ihealthlabs.eu/OpenApiV2/OAuthv2/userauthorization/.
        /// </summary>
        internal static string urlauthorization {
            get {
                return ResourceManager.GetString("urlauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a http://localhost:8080/HendoBackend_war_exploded/request/.
        /// </summary>
        internal static string urlbackendtest {
            get {
                return ResourceManager.GetString("urlbackendtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://openapi.ihealthlabs.eu/openapiv2/user/{0}/glucose.json/.
        /// </summary>
        internal static string urlbgdata {
            get {
                return ResourceManager.GetString("urlbgdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/glucose.json/.
        /// </summary>
        internal static string urlbgdataclient {
            get {
                return ResourceManager.GetString("urlbgdataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://openapi.ihealthlabs.eu/openapiv2/user/{0}/spo2.json/.
        /// </summary>
        internal static string urlbodata {
            get {
                return ResourceManager.GetString("urlbodata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/spo2.json/.
        /// </summary>
        internal static string urlbodataclient {
            get {
                return ResourceManager.GetString("urlbodataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://openapi.ihealthlabs.eu/openapiv2/user/{0}/bp.json/.
        /// </summary>
        internal static string urlbpdata {
            get {
                return ResourceManager.GetString("urlbpdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/bp.json/.
        /// </summary>
        internal static string urlbpdataclient {
            get {
                return ResourceManager.GetString("urlbpdataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/user/{0}/food.json/.
        /// </summary>
        internal static string urlfooddata {
            get {
                return ResourceManager.GetString("urlfooddata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/food.json/.
        /// </summary>
        internal static string urlfooddataclient {
            get {
                return ResourceManager.GetString("urlfooddataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:1025/iHendoTotem/index.aspx.
        /// </summary>
        internal static string urlindex {
            get {
                return ResourceManager.GetString("urlindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:1025/iHendoTotem/login.aspx.
        /// </summary>
        internal static string urllogin {
            get {
                return ResourceManager.GetString("urllogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:1025/iHendoTotem/measurements.aspx.
        /// </summary>
        internal static string urlmeasures {
            get {
                return ResourceManager.GetString("urlmeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:1025/iHendoTotem/register.aspx.
        /// </summary>
        internal static string urlregister {
            get {
                return ResourceManager.GetString("urlregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/user/{0}/sport.json/.
        /// </summary>
        internal static string urlsportdata {
            get {
                return ResourceManager.GetString("urlsportdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/sport.json/.
        /// </summary>
        internal static string urlsportdataclient {
            get {
                return ResourceManager.GetString("urlsportdataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/user/{0}/sleep.json/.
        /// </summary>
        internal static string urlsrdata {
            get {
                return ResourceManager.GetString("urlsrdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/sleep.json/.
        /// </summary>
        internal static string urlsrdataclient {
            get {
                return ResourceManager.GetString("urlsrdataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://localhost:1025/iHendoTotem/tokencallback.aspx.
        /// </summary>
        internal static string urltokencallback {
            get {
                return ResourceManager.GetString("urltokencallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/user/{0}.json/.
        /// </summary>
        internal static string urluserdata {
            get {
                return ResourceManager.GetString("urluserdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/userinfo.json/.
        /// </summary>
        internal static string urluserdataclient {
            get {
                return ResourceManager.GetString("urluserdataclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://openapi.ihealthlabs.eu/openapiv2/user/{0}/weight.json/.
        /// </summary>
        internal static string urlweightdata {
            get {
                return ResourceManager.GetString("urlweightdata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a https://api.ihealthlabs.com:8443/openapiv2/application/weight.json/.
        /// </summary>
        internal static string urlweightdataclient {
            get {
                return ResourceManager.GetString("urlweightdataclient", resourceCulture);
            }
        }
    }
}
